language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
sudo: required
services:
  - docker
before_install:
  - docker pull postgres
env:
  - DOCKER_API=1.20
script: python setup.py test
after_success:
  - codecov
